package com.rm.business_lib.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.rm.business_lib.db.download.DownloadAudio;
import com.rm.business_lib.db.download.DownloadChapter;

import com.rm.business_lib.db.DownloadAudioDao;
import com.rm.business_lib.db.DownloadChapterDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadAudioDaoConfig;
    private final DaoConfig downloadChapterDaoConfig;

    private final DownloadAudioDao downloadAudioDao;
    private final DownloadChapterDao downloadChapterDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloadAudioDaoConfig = daoConfigMap.get(DownloadAudioDao.class).clone();
        downloadAudioDaoConfig.initIdentityScope(type);

        downloadChapterDaoConfig = daoConfigMap.get(DownloadChapterDao.class).clone();
        downloadChapterDaoConfig.initIdentityScope(type);

        downloadAudioDao = new DownloadAudioDao(downloadAudioDaoConfig, this);
        downloadChapterDao = new DownloadChapterDao(downloadChapterDaoConfig, this);

        registerDao(DownloadAudio.class, downloadAudioDao);
        registerDao(DownloadChapter.class, downloadChapterDao);
    }
    
    public void clear() {
        downloadAudioDaoConfig.clearIdentityScope();
        downloadChapterDaoConfig.clearIdentityScope();
    }

    public DownloadAudioDao getDownloadAudioDao() {
        return downloadAudioDao;
    }

    public DownloadChapterDao getDownloadChapterDao() {
        return downloadChapterDao;
    }

}
