package com.rm.business_lib.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.rm.business_lib.db.audiosort.DetailAudioSort;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DETAIL_AUDIO_SORT".
*/
public class DetailAudioSortDao extends AbstractDao<DetailAudioSort, Long> {

    public static final String TABLENAME = "DETAIL_AUDIO_SORT";

    /**
     * Properties of entity DetailAudioSort.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Audio_id = new Property(0, Long.class, "audio_id", true, "_id");
        public final static Property Sort = new Property(1, String.class, "sort", false, "SORT");
    }


    public DetailAudioSortDao(DaoConfig config) {
        super(config);
    }
    
    public DetailAudioSortDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DETAIL_AUDIO_SORT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: audio_id
                "\"SORT\" TEXT);"); // 1: sort
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DETAIL_AUDIO_SORT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DetailAudioSort entity) {
        stmt.clearBindings();
 
        Long audio_id = entity.getAudio_id();
        if (audio_id != null) {
            stmt.bindLong(1, audio_id);
        }
 
        String sort = entity.getSort();
        if (sort != null) {
            stmt.bindString(2, sort);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DetailAudioSort entity) {
        stmt.clearBindings();
 
        Long audio_id = entity.getAudio_id();
        if (audio_id != null) {
            stmt.bindLong(1, audio_id);
        }
 
        String sort = entity.getSort();
        if (sort != null) {
            stmt.bindString(2, sort);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DetailAudioSort readEntity(Cursor cursor, int offset) {
        DetailAudioSort entity = new DetailAudioSort( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // audio_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // sort
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DetailAudioSort entity, int offset) {
        entity.setAudio_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSort(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DetailAudioSort entity, long rowId) {
        entity.setAudio_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DetailAudioSort entity) {
        if(entity != null) {
            return entity.getAudio_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DetailAudioSort entity) {
        return entity.getAudio_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
